(() => {
  const roleKey='userRole', themeKey='themeMode';
  const currentPage=window.location.pathname.split('/').pop()||'index.html', root=document.documentElement;
  const isLoginPage=n=>n===''||n==='Login.html'||n==='index.html';
  const toast=(message,type='info',timeout=3000)=>{const o=document.getElementById('siteToast');if(o)o.remove();const t=document.createElement('div');t.id='siteToast';t.textContent=message;Object.assign(t.style,{position:'fixed',right:'16px',bottom:'16px',padding:'10px 14px',borderRadius:'8px',boxShadow:'0 6px 16px rgba(0,0,0,.12)',zIndex:9999,color:'#fff',fontWeight:600,minWidth:'140px',textAlign:'center',background:type==='error'?'#b91c1c':type==='success'?'#047857':'#2563EB'});document.body.appendChild(t);setTimeout(()=>{t.style.transition='opacity .25s';t.style.opacity='0';setTimeout(()=>t.remove(),250)},timeout)};
  function applyTheme(theme){root.dataset.theme=theme;localStorage.setItem(themeKey,theme);const b=document.getElementById('themeToggleBtn');if(!b)return;const d=theme==='dark';b.innerHTML=isLoginPage(currentPage)?(d?'<span class="icon">☀️</span>':'<span class="icon">🌙</span>'):(d?'<span class="icon">☀️</span><span class="label">Light mode</span>':'<span class="icon">🌙</span><span class="label">Dark mode</span>');b.setAttribute('aria-label',d?'Switch to light mode':'Switch to dark mode');b.classList.toggle('login-toggle',isLoginPage(currentPage));}
  function buildThemeToggle(){if(document.getElementById('themeToggleBtn'))return;const b=document.createElement('button');b.id='themeToggleBtn';b.type='button';b.className='theme-toggle';b.onclick=()=>applyTheme(root.dataset.theme==='dark'?'light':'dark');const n=document.querySelector('nav');if(n)n.appendChild(b);else document.body.appendChild(b);applyTheme(localStorage.getItem(themeKey)||'light');}
  function passwordToggles(){document.querySelectorAll('input[type="password"]').forEach(input=>{if(input.dataset.hasToggle)return;input.dataset.hasToggle='1';const w=document.createElement('div');w.className='input-with-toggle';w.style.position='relative';input.parentNode.insertBefore(w,input);w.appendChild(input);const b=document.createElement('button');b.type='button';b.className='pwd-toggle modern';b.setAttribute('aria-label','Show password');b.textContent='◉';Object.assign(b.style,{position:'absolute',right:'10px',top:'50%',transform:'translateY(-50%)',background:'rgba(37,99,235,.06)',border:'none',cursor:'pointer',width:'48px',height:'44px',borderRadius:'8px',color:'#2563EB',opacity:'.6'});b.onclick=()=>{const show=input.type==='password';input.type=show?'text':'password';b.textContent=show?'◌':'◉';b.setAttribute('aria-label',show?'Hide password':'Show password');input.focus()};w.appendChild(b);});}
  function roleNav(){const role=localStorage.getItem(roleKey),links=[...document.querySelectorAll('nav a[href]')];links.forEach((link,i)=>{let href=link.getAttribute('href')||'',text=link.textContent.trim().toLowerCase();const isHome=text==='home'||/(?:^|\/)Home\.html$/i.test(href)||(i===0&&/(?:^|\/)(?:index|Login)\.html$/i.test(href));const isAuth=text==='logout'||text==='login'||/(?:^|\/)(?:index|Login)\.html$/i.test(href)||href==='/';if(isHome){link.href='Home.html';link.textContent='Home';}else if(isAuth){link.href='../index.html';link.textContent=role?'Logout':'Login';if(role&&!link.dataset.logoutBound){link.dataset.logoutBound='1';link.onclick=e=>{e.preventDefault();localStorage.removeItem(roleKey);localStorage.removeItem('username');toast('Signed out');setTimeout(()=>location.href='../index.html',200)}}}href=link.getAttribute('href')||'';const a=/Admin_/.test(href)||href==='Admin_Dashboard1.html',t=/Teacher_/.test(href)||href==='Teacher_Dashboard.html'||href==='Teachers_Assigned_Complaint.html',s=/Student_/.test(href)||href==='Student_Dashboard.html',pub=isHome||isAuth;if(!role)link.style.display=pub?'inline-block':'none';else if(role==='student')link.style.display=a||t?'none':'inline-block';else if(role==='teacher')link.style.display=a||s?'none':'inline-block';else if(role==='admin')link.style.display=t||s?'none':'inline-block';});}
  function badge(){const role=localStorage.getItem(roleKey),username=localStorage.getItem('username'),nav=document.querySelector('nav');if(!nav)return;let b=document.getElementById('userBadge');if(!b){b=document.createElement('div');b.id='userBadge';Object.assign(b.style,{marginLeft:'12px',fontSize:'14px',color:'#fff',alignSelf:'center'});nav.appendChild(b)}if(!role){b.textContent='';b.style.display='none';return}b.textContent=username?`${username} • ${role.charAt(0).toUpperCase()+role.slice(1)}`:role.charAt(0).toUpperCase()+role.slice(1);b.style.display='block';}
  function protect(){const role=localStorage.getItem(roleKey),a=['Admin_Dashboard1.html','Admin_All_Complaints.html','Admin_Complaint_Details.html','Admin_Confirm_Resolution.html','Admin_Update_Status.html','Assign_Complaint.html'],t=['Teacher_Dashboard.html','Teacher_Complaint_Details.html','Teacher_Resolved_Complaint.html','Teacher_Sent_To_Admin.html','Teachers_Assigned_Complaint.html'],s=['Student_Dashboard.html','Submit_Complaint.html','My_Complaints.html','Submission_Guide.html'],d=role==='student'?'Student_Dashboard.html':role==='teacher'?'Teacher_Dashboard.html':role==='admin'?'Admin_Dashboard1.html':'../index.html';if(a.includes(currentPage)&&role!=='admin')location.href=d;if(t.includes(currentPage)&&role!=='teacher')location.href=d;if(s.includes(currentPage)&&role!=='student')location.href=d;}
  applyTheme(localStorage.getItem(themeKey)||'light');buildThemeToggle();roleNav();badge();passwordToggles();protect();
})();
